#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for storage/page
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header: /usr/local/cvsroot/postgres95/src/backend/storage/page/Makefile.inc,v 1.1.1.1 1996/07/09 06:21:58 scrappy Exp $
#
#-------------------------------------------------------------------------

SUBSRCS+= bufpage.c itemptr.c


