/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <time.h>

#include "date.h"

long *get_date_1_svc(void *argp, struct svc_req *rqstp)
{
	static long result;

	/*
     * insert server code here
     */
	// 加一句这个，运行后产生的是从1970年1月1日0时0分0秒到此时的秒数
	result = time((long *)0);

	return &result;
}
