#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for tools/mkldexport
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header: /usr/local/cvsroot/postgres95/src/tools/mkldexport/Makefile,v 1.1.1.1 1996/07/09 06:22:32 scrappy Exp $
#
#-------------------------------------------------------------------------

SHPROG=mkldexport

MKDIR=	../../mk
include ../../Makefile.global
include $(MKDIR)/postgres.mk

include $(MKDIR)/postgres.shell.mk
