#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for utils/hash
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header: /usr/local/cvsroot/postgres95/src/backend/utils/hash/Makefile.inc,v 1.1.1.1 1996/07/09 06:22:08 scrappy Exp $
#
#-------------------------------------------------------------------------

SUBSRCS+= dynahash.c hashfn.c
