#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for test suites
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header: /usr/local/cvsroot/postgres95/src/test/Makefile,v 1.1.1.1 1996/07/09 06:22:20 scrappy Exp $
#
#-------------------------------------------------------------------------

SUBDIR= bench regress

include ../mk/postgres.subdir.mk


