#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for utils/cache
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header: /usr/local/cvsroot/postgres95/src/backend/utils/cache/Makefile.inc,v 1.1.1.1 1996/07/09 06:22:06 scrappy Exp $
#
#-------------------------------------------------------------------------

SUBSRCS+= catcache.c inval.c rel.c relcache.c syscache.c lsyscache.c fcache.c

