#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for utils/fmgr
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header: /usr/local/cvsroot/postgres95/src/backend/utils/fmgr/Makefile.inc,v 1.1.1.1 1996/07/09 06:22:07 scrappy Exp $
#
#-------------------------------------------------------------------------

SUBSRCS+= dfmgr.c fmgr.c 

