#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for storage/smgr
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header: /usr/local/cvsroot/postgres95/src/backend/storage/smgr/Makefile.inc,v 1.1.1.1 1996/07/09 06:21:59 scrappy Exp $
#
#-------------------------------------------------------------------------

SUBSRCS+= md.c mm.c smgr.c smgrtype.c
