#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for optimizer/prep
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header: /usr/local/cvsroot/postgres95/src/backend/optimizer/prep/Makefile.inc,v 1.1.1.1 1996/07/09 06:21:37 scrappy Exp $
#
#-------------------------------------------------------------------------

SUBSRCS+= archive.c prepqual.c preptlist.c prepunion.c
