#ifndef AIO_LEARN_H
#define AIO_LEARN_H

#include "../lib/demo.h"
DEMO_MAIN_DECL(1);
DEMO_MAIN_DECL(2);
DEMO_MAIN_DECL(3);
DEMO_MAIN_DECL(4);
DEMO_MAIN_DECL(5);
DEMO_MAIN_DECL(6);
DEMO_MAIN_DECL(7);
DEMO_MAIN_DECL(8);
DEMO_MAIN_DECL(9);
DEMO_MAIN_DECL(10);
DEMO_MAIN_DECL(11);
DEMO_MAIN_DECL(argv_test);
DEMO_MAIN_DECL(do_while);
DEMO_MAIN_DECL(VA_ARGS);
DEMO_MAIN_DECL(sizeof);
DEMO_MAIN_DECL(int);
DEMO_MAIN_DECL(uint64);
DEMO_MAIN_DECL(arr);
DEMO_MAIN_DECL(continue);

#endif
