#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for storage/file
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header: /usr/local/cvsroot/postgres95/src/backend/storage/file/Makefile.inc,v 1.1.1.1 1996/07/09 06:21:55 scrappy Exp $
#
#-------------------------------------------------------------------------

SUBSRCS+= fd.c
