#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for utils/sort
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header: /usr/local/cvsroot/postgres95/src/backend/utils/sort/Makefile.inc,v 1.1.1.1 1996/07/09 06:22:10 scrappy Exp $
#
#-------------------------------------------------------------------------

SUBSRCS+= lselect.c psort.c
