#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for utils/mmgr
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header: /usr/local/cvsroot/postgres95/src/backend/utils/mmgr/Makefile.inc,v 1.1.1.1 1996/07/09 06:22:09 scrappy Exp $
#
#-------------------------------------------------------------------------

SUBSRCS+= aset.c mcxt.c palloc.c portalmem.c oset.c

