#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for storage/lmgr
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header: /usr/local/cvsroot/postgres95/src/backend/storage/lmgr/Makefile.inc,v 1.1.1.1 1996/07/09 06:21:55 scrappy Exp $
#
#-------------------------------------------------------------------------

SUBSRCS+= lmgr.c lock.c multi.c proc.c single.c
