#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for access/transam
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header: /usr/local/cvsroot/postgres95/src/backend/access/transam/Makefile.inc,v 1.1.1.1 1996/07/09 06:21:13 scrappy Exp $
#
#-------------------------------------------------------------------------

SUBSRCS+= transam.c transsup.c varsup.c xact.c xid.c 
