#ifndef AIO_LEARN_H
#define AIO_LEARN_H

#include "../lib/demo.h"
DEMO_MAIN_DECL(splice);
DEMO_MAIN_DECL(splice1);
DEMO_MAIN_DECL(open);
DEMO_MAIN_DECL(open1);
DEMO_MAIN_DECL(file_flags);
DEMO_MAIN_DECL(fcntl);
DEMO_MAIN_DECL(F_WRLCK);
DEMO_MAIN_DECL(creat);
DEMO_MAIN_DECL(fallocate);
DEMO_MAIN_DECL(FD_CLOEXEC);
DEMO_MAIN_DECL(O_CLOEXEC);
DEMO_MAIN_DECL(SSH1);
DEMO_MAIN_DECL(SSH2);
DEMO_MAIN_DECL(open_3);
DEMO_MAIN_DECL(open_4);
DEMO_MAIN_DECL(open_5);
DEMO_MAIN_DECL(open_6);

#endif
