#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for access/index
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header: /usr/local/cvsroot/postgres95/src/backend/access/index/Makefile.inc,v 1.1.1.1 1996/07/09 06:21:11 scrappy Exp $
#
#-------------------------------------------------------------------------

SUBSRCS+= genam.c indexam.c istrat.c
