#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for optimizer/plan
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header: /usr/local/cvsroot/postgres95/src/backend/optimizer/plan/Makefile.inc,v 1.1.1.1 1996/07/09 06:21:37 scrappy Exp $
#
#-------------------------------------------------------------------------

SUBSRCS+= createplan.c initsplan.c planmain.c planner.c \
	 setrefs.c
