#-------------------------------------------------------------------------
#
# Makefile.inc--
#    Makefile for utils/error
#
# Copyright (c) 1994, Regents of the University of California
#
#
# IDENTIFICATION
#    $Header: /usr/local/cvsroot/postgres95/src/backend/utils/error/Makefile.inc,v 1.1.1.1 1996/07/09 06:22:07 scrappy Exp $
#
#-------------------------------------------------------------------------

SUBSRCS+= assert.c elog.c exc.c excabort.c excid.c format.c
